name: Update IPTV playlists

on:
    push:
        branches: ["m3u"]
        paths: "scripts/update_IPTV_list.sh"
    pull_request:
        branches: ["m3u"]
        paths: "scripts/update_IPTV_list.sh"
    schedule:
        - cron: "0 20 * * *"
    workflow_dispatch:
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: "m3u"

            - name: Update time
              run: |
                  echo "update_time=$(TZ="Asia/Bangkok" date "+%d-%m-%y %I:%M %p")" >> GITHUB_ENV
            - name: Update
              run: scripts/update_IPTV_list.sh

            - name: Push to Github
              run: |
                  git config --global user.name ${{ secrets.MY_USERNAME }}
                  git config --global user.email ${{ secrets.MY_EMAIL }}
                  git checkout --orphan m3u_modified
                  git add .
                  git commit -m "Update ${{ env.update_time }}"
                  git branch -D m3u
                  git branch -m m3u
                  git push -f origin m3u
