name: Update IPTV playlists

on:
    push:
        branches: ["main"]
        paths: "scripts/update_IPTV_list.sh"
    pull_request:
        branches: ["main"]
        paths: "scripts/update_IPTV_list.sh"
    schedule:
        - cron: "0 8,20 * * *"
    workflow_dispatch:
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Update time
              run: |
                  echo "update_time=$(TZ="Asia/Bangkok" date "+%d-%m-%y at %I:%M %p")" >> $GITHUB_ENV

            - name: Update playlists
              run: scripts/update_IPTV_list.sh

            - name: Update time in README
              run: |
                  mv -f README_m3u.md README.md
                  rm -rf ./.github ./scripts .gitignore .whitesource renovate.json
                  sed -i "s/-   \*\*Time:\*\*.*/-   \*\*Time:\*\* ${{ env.update_time }}/" ./README.md

            - name: Push to Github
              run: |
                  git config --global user.name ${{ secrets.MY_USERNAME }}
                  git config --global user.email ${{ secrets.MY_EMAIL }}
                  git checkout --orphan m3u_modified
                  git add .
                  git commit -m "Updated on ${{ env.update_time }}"
                  if git ls-remote --exit-code --heads origin m3u; then
                    git push origin --delete m3u
                  fi
                  git branch -m m3u
                  git push -f origin m3u
